In [1]:
import numpy as np

d1 = 9
d2 = 8

A = np.array([[d1, d2],
              [d2, d1]])

print(A)
print(A)


[[9 8]
 [8 9]]
[[9 8]
 [8 9]]


In [2]:
print(A)

print("Shape of A:", A.shape)

det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

rank_A = np.linalg.matrix_rank(A)
print("Rank of A:", rank_A)

eig_A = np.linalg.eigvals(A)
print("Eigenvalues of A:", eig_A)

if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:\n", inv_A)
else:
    print("Matrix A is not invertible (determinant = 0)")


[[9 8]
 [8 9]]
Shape of A: (2, 2)
Determinant of A: 17.00000000000001
Rank of A: 2
Eigenvalues of A: [17.  1.]
Inverse of A:
 [[ 0.52941176 -0.47058824]
 [-0.47058824  0.52941176]]


In [3]:

B = A.copy()
B[0, 0] = B[0, 0] + 1

print("\n===== MATRIX B (Changed A[0,0] +1) =====")
print("Changed element: A[0,0] from 9 to 10")
print(B)




===== MATRIX B (Changed A[0,0] +1) =====
Changed element: A[0,0] from 9 to 10
[[10  8]
 [ 8  9]]


In [4]:

print("\n--- Properties of Matrix B ---")

print("Shape of B:", B.shape)

det_B = np.linalg.det(B)
print("Determinant of B:", det_B)

rank_B = np.linalg.matrix_rank(B)
print("Rank of B:", rank_B)

eig_B = np.linalg.eigvals(B)
print("Eigenvalues of B:", eig_B)

if det_B != 0:
    inv_B = np.linalg.inv(B)
    print("Inverse of B:\n", inv_B)
else:
    print("Matrix B is not invertible (determinant = 0)")


--- Properties of Matrix B ---
Shape of B: (2, 2)
Determinant of B: 26.000000000000004
Rank of B: 2
Eigenvalues of B: [17.51560977  1.48439023]
Inverse of B:
 [[ 0.34615385 -0.30769231]
 [-0.30769231  0.38461538]]


In [5]:
print("\n===== COMPARISON =====")

print("Determinant Change:", det_A, "->", det_B)
print("Rank Change:", rank_A, "->", rank_B)
print("Eigenvalues Change:")
print("A:", eig_A)
print("B:", eig_B)

if abs(det_B) > abs(det_A):
    print("Matrix B is numerically more stable to invert (larger determinant).")
else:
    print("Matrix A is numerically more stable to invert.")


===== COMPARISON =====
Determinant Change: 17.00000000000001 -> 26.000000000000004
Rank Change: 2 -> 2
Eigenvalues Change:
A: [17.  1.]
B: [17.51560977  1.48439023]
Matrix B is numerically more stable to invert (larger determinant).
